language: elixir

sudo: false

elixir:
  - '1.6.1'
  - '1.7.0'
  - '1.8.0'

otp_release:
  - '20.0'

env:
  - MIX_ENV="test"

script:
  - mix compile --warnings-as-errors
  - mix format --check-formatted --dry-run
  - mix credo
  - mix coveralls.html --max-cases 1
  - mix dialyzer --halt-exit-status

cache:
  directories:
    - _build
    - deps
