language: elixir

sudo: false

elixir:
  - '1.7.4'
  - '1.8.1'

otp_release:
  - '21.2'

env:
  - MIX_ENV="test"

script:
  - mix compile --warnings-as-errors
  - mix format --check-formatted --dry-run
  - mix credo
  - mix coveralls.html --max-cases 1

cache:
  directories:
    - _build
    - deps
